#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-textfsm
Version  : 1.1.3
Release  : 13
URL      : https://files.pythonhosted.org/packages/b8/bf/c9147d29c5a3ff4c1c876e16ea02f6d4e4f35ba1bcbb2ac80a254924f0aa/textfsm-1.1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/b8/bf/c9147d29c5a3ff4c1c876e16ea02f6d4e4f35ba1bcbb2ac80a254924f0aa/textfsm-1.1.3.tar.gz
Summary  : Python module for parsing semi-structured text into python tables.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-textfsm-bin = %{version}-%{release}
Requires: pypi-textfsm-license = %{version}-%{release}
Requires: pypi-textfsm-python = %{version}-%{release}
Requires: pypi-textfsm-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(future)
BuildRequires : pypi(six)

%description
=======
        
        Python module which implements a template based state machine for parsing
        semi-formatted text. Originally developed to allow programmatic access to
        information returned from the command line interface (CLI) of networking
        devices.
        
        The engine takes two inputs - a template file, and text input (such as command
        responses from the CLI of a device) and returns a list of records that contains
        the data parsed from the text.
        
        A template file is needed for each uniquely structured text input. Some examples
        are provided with the code and users are encouraged to develop their own.
        
        By developing a pool of template files, scripts can call TextFSM to parse useful
        information from a variety of sources. It is also possible to use different
        templates on the same data in order to create different tables (or views).
        
        TextFSM was developed internally at Google and released under the Apache 2.0
        licence for the benefit of the wider community.

%package bin
Summary: bin components for the pypi-textfsm package.
Group: Binaries
Requires: pypi-textfsm-license = %{version}-%{release}

%description bin
bin components for the pypi-textfsm package.


%package license
Summary: license components for the pypi-textfsm package.
Group: Default

%description license
license components for the pypi-textfsm package.


%package python
Summary: python components for the pypi-textfsm package.
Group: Default
Requires: pypi-textfsm-python3 = %{version}-%{release}

%description python
python components for the pypi-textfsm package.


%package python3
Summary: python3 components for the pypi-textfsm package.
Group: Default
Requires: python3-core
Requires: pypi(future)
Requires: pypi(six)
Provides: pypi(textfsm)

%description python3
python3 components for the pypi-textfsm package.


%prep
%setup -q -n textfsm-1.1.3
cd %{_builddir}/textfsm-1.1.3
pushd ..
cp -a textfsm-1.1.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1657206682
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-textfsm
cp %{_builddir}/textfsm-1.1.3/COPYING %{buildroot}/usr/share/package-licenses/pypi-textfsm/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/textfsm-1.1.3/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-textfsm/a8f3e29d5eab4420318de979754f5637d4bf2c3f
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/textfsm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-textfsm/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-textfsm/a8f3e29d5eab4420318de979754f5637d4bf2c3f

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
